### PR TITLE
doc(readme): described how to undo Spotify theme. #134

### PR DESCRIPTION
**Pull request by AndreasBackx**
I've followed your way of commit messages. Could you confirm that these folder locations are used in all of the distros?

### CODE REVIEW

**Comment by actionless** [comment]
> Could you confirm that these folder locations are used in all of the distros?

`/usr/share/spotify/Apps` could depend on distro

**Comment by AndreasBackx** [comment]
@actionless I've used that one because it was set as the default path in oomoxify. Perhaps I can change the line to say that if they passed a different Spotify install location to oomoxify, that they use that instead?

**Comment by actionless** [comment]
yup, i guess so

**Comment by actionless** [comment]
whatever, it's still better than not mentioning that at all

thanks!

**Pull request merged**
