### PR TITLE
Improve Materia checkbox preview

### PR DESCRIPTION
**Pull request by nana-4**
Before:

image

After:

image

### CODE REVIEW

**Comment by actionless** [comment]
thanks, it's much better now

how did you made it? i've just copied a part from original assets.svg

**Comment by nana-4** [comment]
I just added `fill="#%SEL_BG%"` to [`materia-theme/src/gtk/assets/scalable/checkbox-checked-symbolic.svg`](https://github.com/nana-4/materia-theme/blob/master/src/gtk/assets/scalable/checkbox-checked-symbolic.svg) :)

**Comment by actionless** [comment]
i didn't noticed there are any other svg assets than assets.svg

**Comment by nana-4** [comment]
They are used with `-gtk-recolor()`, so they have no color :smile:

**Pull request merged**
