### PR TITLE
Updated Suru++ submodules and new April colourschemes

### PR DESCRIPTION
**Pull request by gusbemacbe**
* Updated Suru++ and Suru++ Asprómauros submodules
* New April colourschemes:
  * Easter 1
  * Easter 2
  * International Day of Astronomy (28 April)

### CODE REVIEW

**Comment by actionless** [comment]
and what's with Materia submodule?

**Comment by gusbemacbe** [comment]
Ah, I didn't do it. It must be because of <code>git clone... blablabla <b>--recursive</b></code> as you have taught me before.

**Comment by actionless** [comment]
nice work on the themes btw!
although i'd make the `Border` in `easter2` theme mb just slightly less contrast, to look the same as bottom shadow of home icon preview of the same theme

**Comment by actionless** [comment]
re materia: it seems what your local fork is out of date

just don't stage materia to commit

don't do `git commit -a`
but instead do `git add` and normal `git commit` to avoid accidentally adding unwanted changes to the commit

**Comment by actionless** [comment]
for example now you can do `git reset --soft HEAD~2`

`git reset`


`git add -i`


`git commit`

**Comment by actionless** [comment]
did it worked for you?

**Comment by gusbemacbe** [comment]
Yes, it worked, I unstaged `plugins_theme_materia` and staged only the colourschemes and two Suru++ submodules, using GitKraken, just after `git rebase`,

**Comment by gusbemacbe** [comment]
>  although i'd make the `Border` in `easter2` theme mb just slightly less contrast, to look the same as bottom shadow of home icon preview of the same theme

Are you referring to:

```
WM_BORDER_FOCUS=2e2f27
WM_BORDER_UNFOCUS=b6bb7b
``` 
?

**Comment by gusbemacbe** [comment]
Why is Travis CI taking a lot of time to finish the analysis?

**Comment by actionless** [comment]
regarding Materia it looks fine now, thanks!


regarding travis it seems to be some bug with github integration with travis:

on travis website build marked as passed in about 3 minutes https://travis-ci.com/themix-project/oomox/builds/105559514

**Comment by actionless** [comment]
and regarding `easter2`: i meant `ARC_WIDGET_BORDER_COLOR`

**Comment by gusbemacbe** [comment]
I can not see the border in the preview.

**Comment by gusbemacbe** [comment]
I switch from Arc to Oomox, I can see the border.

**Comment by gusbemacbe** [comment]
I understood now

**Comment by gusbemacbe** [comment]
I have just updated the Arc border in `easter2` colourscheme.

**Comment by actionless** [comment]
border color still looks somehow off (which could be more something to improve in color-changing scripts for arc theme, seems as you see some other borders are inherited from the surrounding widgets) so i am merging this


2019-03-24--1553412734_2684x1522_scrot

**Pull request merged**
