### PR TITLE
New colour schemes

### PR DESCRIPTION
**Pull request by gusbemacbe**
Hello @actionless !

I created the new three colour schemes:

1. 90ssumer, based on colour schemes of years 80s and 90s, as the success of Technotronic, nostalgic famous advertising of the TV, as the Russian personal trainer, a Japanese couple adverting the knife, cutting the fish, a woman surfing with a sport jet, etc. 
2. 8march - Woman's International Day, inspired by the colour schemes of 90s summer (90s Russian personal trainer in the TV), according to #214.
3. autumn - Autumn, inspired by the colour schemes of 90s summer and 90s Technotronic, according to #214 .

### CODE REVIEW

**Comment by actionless** [comment]
thanks! they look nice

the only think i would improve -- in Autumn theme Accent color seems to me not contrast enough (ie checked/unchecked checkbox for example)

**Comment by gusbemacbe** [comment]
> what about slightly darker color for the accents, what do you think?

I will check.

**Comment by gusbemacbe** [comment]
Ready, @actionless , see if it improved.

**Comment by actionless** [comment]
thanks a lot!

btw, 90ssummer theme gives that nice feeling what buttons are made from the same plastic as plastic toys in 90s :) i was trying to achieve a similar effect in `Pop Art/unit01c` theme:) :+1:

**Comment by gusbemacbe** [comment]
Thank you a lot!

> btw, 90ssummer theme gives that nice feeling what buttons are made from the same plastic as plastic toys in 90s :) i was trying to achieve a similar effect in `Pop Art/unit01c` theme:) +1

These plastic toys and most of products (clothes, toys, electronics, etc.) are based in the main colours scheme came from 90s TV programs and from 90s Technotronic. 

Too bad that I exported only GTK3+, I wanted to export to KDE. I have to research how to convert GTK3 to QT.

**Comment by actionless** [comment]
oomox export `qt5ct` palette by default

also more about conversion between KDE and oomox palettes here, i need some help from KDE user to finish the plugin:

https://github.com/themix-project/oomox/issues/54#issuecomment-454997338

**Comment by actionless** [comment]
your qt5ct issue not related to KDE colors support plugin since the plugin itself is not implemented yet

to use qt5ct theme with oomox choose Fusion and choose oomox color palette in qt5ct settings, it have nothing to do with gtk2

**Pull request merged**
